#
# Site settings
#
title:			alfabravo.org
email:			arturo.borrero.glez@gmail.com
description: >
  Este es el blog 'alfabravo', con tematica relacionada con aventuras,
  viajes y experiencias.
baseurl:		""
url:			"http://alfabravo.org"
twitter_username:	arturoborrero
github_username:	aborrero

#
# Build settings
#
markdown:		kramdown
# to show future post, run 'jekyll serve --future'
future:			false

#
# Pagination config
#
gems:			[jekyll-paginate]
paginate:		8
paginate_path:		"/page:num/"


#
# Other settings
#
excerpt_separator:	<!--more-->
